services:
  directus:
    image: directus/directus:latest
    restart: unless-stopped
    ports:
      - "8355:8055"
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
    env_file:
      - .env
    environment:
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      STORAGE_LOCAL_ROOT: '/directus/uploads'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: '*'  # Allow all origins in development
      CORS_METHODS: 'GET,POST,PATCH,DELETE'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'
      CORS_CREDENTIALS: 'true'
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      KEY: ${KEY}
      SECRET: ${SECRET}
      STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
      PUBLIC_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
      ADMIN_ACCESS_TOKEN: ${DIRECTUS_STATIC_TOKEN}
      AUTH_PROVIDERS: ''
      AUTH_DISABLE_DEFAULT: 'false'
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=3", "--spider", "http://localhost:8055/server/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
        NEXT_PUBLIC_DIRECTUS_TOKEN: ${DIRECTUS_STATIC_TOKEN}
        AUTH0_SECRET: ${AUTH0_SECRET}
        AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        AUTH0_SCOPE: ${AUTH0_SCOPE}
        AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
        AUTH0_MGMT_IDENTIFIER: ${AUTH0_MGMT_IDENTIFIER}
        APP_BASE_URL: ${APP_BASE_URL}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
        DIRECTUS_ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
        DIRECTUS_ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
        DIRECTUS_INTERNAL_URL: ${DIRECTUS_INTERNAL_URL}
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    ports:
      - "3300:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      # Auth0 Configuration
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_SCOPE: ${AUTH0_SCOPE}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_MGMT_IDENTIFIER: ${AUTH0_MGMT_IDENTIFIER}
      # Application URLs
      APP_BASE_URL: ${NEXT_PUBLIC_APP_URL}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      # Directus Configuration
      NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
      DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
      DIRECTUS_ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      DIRECTUS_ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      DIRECTUS_INTERNAL_URL: ${DIRECTUS_INTERNAL_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - directus
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  directus_database:
    name: directus_database
  directus_uploads:
    name: directus_uploads
