name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger option

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import Secrets from Vault
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/zizcon-v2-nextjs/config AUTH0_DOMAIN;
            kv/data/zizcon-v2-nextjs/config AUTH0_ISSUER_BASE_URL;
            kv/data/zizcon-v2-nextjs/config AUTH0_SCOPE;
            kv/data/zizcon-v2-nextjs/config AUTH0_CLIENT_ID;
            kv/data/zizcon-v2-nextjs/config AUTH0_CLIENT_SECRET;
            kv/data/zizcon-v2-nextjs/config AUTH0_AUDIENCE;
            kv/data/zizcon-v2-nextjs/config NEXT_PUBLIC_APP_URL;
            kv/data/zizcon-v2-nextjs/config APP_BASE_URL;
            kv/data/zizcon-v2-nextjs/config AUTH0_CALLBACK_URL;
            kv/data/zizcon-v2-nextjs/config AUTH0_POST_LOGOUT_REDIRECT_URI;
            kv/data/zizcon-v2-nextjs/config AUTH0_SECRET;
            kv/data/zizcon-v2-nextjs/config AUTH0_MGMT_IDENTIFIER;
            kv/data/zizcon-v2-nextjs/config ADMIN_EMAIL;
            kv/data/zizcon-v2-nextjs/config ADMIN_PASSWORD;
            kv/data/zizcon-v2-nextjs/config DIRECTUS_ADMIN_EMAIL;
            kv/data/zizcon-v2-nextjs/config DIRECTUS_ADMIN_PASSWORD;
            kv/data/zizcon-v2-nextjs/config KEY;
            kv/data/zizcon-v2-nextjs/config SECRET;
            kv/data/zizcon-v2-nextjs/config DIRECTUS_STATIC_TOKEN;
            kv/data/zizcon-v2-nextjs/config NEXT_PUBLIC_DIRECTUS_URL;
            kv/data/zizcon-v2-nextjs/config NEXT_PUBLIC_DIRECTUS_TOKEN;
            kv/data/zizcon-v2-nextjs/config DIRECTUS_INTERNAL_URL;
            kv/data/zizcon-v2-nextjs/config STRIPE_SECRET_KEY;

      - name: Deploy to VPS
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/zizcon-v2
            
            # Create temporary .env file for deployment
            echo "# Auth0 Configuration
            AUTH0_DOMAIN=${{ steps.secrets.outputs.AUTH0_DOMAIN }}
            AUTH0_ISSUER_BASE_URL=${{ steps.secrets.outputs.AUTH0_ISSUER_BASE_URL }}
            AUTH0_SCOPE=${{ steps.secrets.outputs.AUTH0_SCOPE }}
            AUTH0_CLIENT_ID=${{ steps.secrets.outputs.AUTH0_CLIENT_ID }}
            AUTH0_CLIENT_SECRET=${{ steps.secrets.outputs.AUTH0_CLIENT_SECRET }}
            AUTH0_AUDIENCE=${{ steps.secrets.outputs.AUTH0_AUDIENCE }}

            # Application URLs
            NEXT_PUBLIC_APP_URL=${{ steps.secrets.outputs.NEXT_PUBLIC_APP_URL }}
            APP_BASE_URL=${{ steps.secrets.outputs.APP_BASE_URL }}
            AUTH0_CALLBACK_URL=${{ steps.secrets.outputs.AUTH0_CALLBACK_URL }}
            AUTH0_POST_LOGOUT_REDIRECT_URI=${{ steps.secrets.outputs.AUTH0_POST_LOGOUT_REDIRECT_URI }}
            AUTH0_SECRET=${{ steps.secrets.outputs.AUTH0_SECRET }}

            # Directus Configuration
            ADMIN_EMAIL=${{ steps.secrets.outputs.ADMIN_EMAIL }}
            ADMIN_PASSWORD=${{ steps.secrets.outputs.ADMIN_PASSWORD }}
            DIRECTUS_ADMIN_EMAIL=${{ steps.secrets.outputs.DIRECTUS_ADMIN_EMAIL }}
            DIRECTUS_ADMIN_PASSWORD=${{ steps.secrets.outputs.DIRECTUS_ADMIN_PASSWORD }}

            # Security
            KEY=${{ steps.secrets.outputs.KEY }}
            SECRET=${{ steps.secrets.outputs.SECRET }}
            DIRECTUS_STATIC_TOKEN=${{ steps.secrets.outputs.DIRECTUS_STATIC_TOKEN }}

            # Directus URLs
            NEXT_PUBLIC_DIRECTUS_URL=${{ steps.secrets.outputs.NEXT_PUBLIC_DIRECTUS_URL }}
            NEXT_PUBLIC_DIRECTUS_TOKEN=${{ steps.secrets.outputs.DIRECTUS_STATIC_TOKEN }}
            AUTH0_MGMT_IDENTIFIER=${{ steps.secrets.outputs.AUTH0_MGMT_IDENTIFIER }}
            DIRECTUS_INTERNAL_URL=${{ steps.secrets.outputs.DIRECTUS_INTERNAL_URL }}" > .env
            
            # Pull latest changes
            git pull origin main
            
            # Rebuild and restart containers
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
            
            # Clean up
            rm .env

      - name: Send deployment notification
        if: always()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: mail.tadeasfort.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          secure: false  # For port 587, we use STARTTLS
          subject: "[${{ job.status }}] Zizcon V2 Deployment - ${{ github.ref_name }}"
          to: ${{ secrets.NOTIFICATION_EMAILS }}
          from: "Zizcon V2 Deployment <noreply@tadeasfort.com>"
          reply_to: noreply@tadeasfort.com
          convert_markdown: true
          html_body: |
            <h1>Deployment Status Report</h1>
            
            <h2>Overview</h2>
            <ul>
              <li><strong>Status</strong>: ${{ job.status }}</li>
              <li><strong>Branch</strong>: ${{ github.ref_name }}</li>
              <li><strong>Commit</strong>: <a href="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}">${{ github.sha }}</a></li>
              <li><strong>Triggered by</strong>: ${{ github.actor }}</li>
            </ul>
            
            <h2>Details</h2>
            <ul>
              <li><strong>Repository</strong>: <a href="${{ github.server_url }}/${{ github.repository }}">${{ github.repository }}</a></li>
              <li><strong>Workflow</strong>: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">${{ github.workflow }}</a></li>
            </ul>
            
            <h2>Links</h2>
            <ul>
              <li><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></li>
              <li><a href="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}">View Commit Details</a></li>
            </ul>
            
            <hr>
            <em>This is an automated message from GitHub Actions</em>
          
          priority: ${{ job.status == 'success' && 'normal' || 'high' }}
          ignore_cert: true